---
- hosts: all
  become: true
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
    #Configure dedicate storage device for Docker engine data directory
    - name: Create a volume group on top of /dev/sda with physical extent size = 32MB
      lvg:
        vg: data
        pvs: /dev/sda
        pesize: 32
    - name: Check if Docker data logical volume exists
      stat:
        path: /dev/data/docker
      register: lvDockerDataExist
    - name: Create a logical volume of 15GiB
      lvol:
        vg: data
        lv: docker
        size: 100%FREE
      when:
        - lvDockerDataExist.stat.exists == False
    - name: Create a ext4 filesystem on /dev/data/docker
      filesystem:
        fstype: ext4
        dev: /dev/data/docker
    - name: mount the lv on /var/lib/docker
      mount:
        path: /var/lib/docker
        src: /dev/data/docker
        fstype: ext4
        state: mounted
  roles:
    - geerlingguy.ntp
    - geerlingguy.docker
  tasks:
    #Add vagrant user to Docker group
    - name: Add the user 'vagrant' to group 'docker'
      user:
        name: vagrant
        groups: docker
        append: yes
    # Calico minimum kernal requirement check
    - name: Ensure Calico minimum kernel modules requirement
      modprobe:
        name: "{{ item }}"
        state: present
      loop: "{{ calico_kernel_modules }}"
